server:
  port: 8000



mybatis:
  #实体类所做包
  type-aliases-package: com.example.demo.pojo
  #mapper.xml所在位置
  mapper-locations: classpath:/mapper/*.xml

spring:
  datasource:
    username: root
    password: tiger
    url: jdbc:mysql://localhost:3306/login?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    #type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver

  mvc:
    view:
      prefix: /WEB-INF/main/
      suffix:
